# Generated by Django 4.2.7 on 2026-01-09 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número de Habitación')),
                ('tipo', models.CharField(choices=[('sencilla', 'Sencilla'), ('doble', 'Doble'), ('suite', 'Suite'), ('presidencial', 'Presidencial')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('limpieza', 'En Limpieza'), ('reservada', 'Reservada')], default='disponible', max_length=20, verbose_name='Estado')),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad (personas)')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Noche')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('servicios', models.TextField(blank=True, help_text='Servicios incluidos (WiFi, TV, etc.)', verbose_name='Servicios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('documento_identidad', models.CharField(max_length=50, unique=True, verbose_name='Documento de Identidad')),
                ('nacionalidad', models.CharField(default='México', max_length=100, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('preferencias', models.TextField(blank=True, help_text='Preferencias especiales del huésped', verbose_name='Preferencias')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('numero_huespedes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Huéspedes')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('checkout', 'Check-out Realizado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('empleado', models.CharField(blank=True, max_length=100, verbose_name='Empleado que realizó el check-out')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Pagado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('danos_observados', models.TextField(blank=True, verbose_name='Daños Observados')),
                ('calificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calificación (1-5)')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='hotel.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Check-out',
                'verbose_name_plural': 'Check-outs',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('empleado', models.CharField(blank=True, max_length=100, verbose_name='Empleado que realizó el check-in')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('documentos_recibidos', models.BooleanField(default=False, verbose_name='Documentos Recibidos')),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Depósito')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='hotel.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
