# Generated by Django 4.2.7 on 2026-04-29 01:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import hotel.tenant_managers


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_huesped_nacionalidad_default_peru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'base_manager_name': 'all_objects', 'ordering': ['-fecha_hora'], 'verbose_name': 'Check-in', 'verbose_name_plural': 'Check-ins'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'base_manager_name': 'all_objects', 'ordering': ['-fecha_hora'], 'verbose_name': 'Check-out', 'verbose_name_plural': 'Check-outs'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'base_manager_name': 'all_objects', 'ordering': ['numero'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='huesped',
            options={'base_manager_name': 'all_objects', 'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Huésped', 'verbose_name_plural': 'Huéspedes'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'base_manager_name': 'all_objects', 'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelManagers(
            name='checkin',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='checkout',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='habitacion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='huesped',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reserva',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', hotel.tenant_managers.AllObjectsManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='huesped',
            name='uniq_huesped_tenant_documento',
        ),
        migrations.RenameIndex(
            model_name='habitacion',
            new_name='hotel_habit_estado_9b2882_idx',
            old_name='hotel_habitacion_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='habitacion',
            new_name='hotel_habit_tipo_eb47ec_idx',
            old_name='hotel_habitacion_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='huesped',
            new_name='hotel_huesp_apellid_0be897_idx',
            old_name='hotel_huesped_apell_nom_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='hotel_reser_fecha_e_bb68a0_idx',
            old_name='hotel_reserva_fechas_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='hotel_reser_estado_b95b96_idx',
            old_name='hotel_reserva_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='hotel_reser_huesped_24a3e0_idx',
            old_name='hotel_reserva_huesped_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='hotel_reser_habitac_6fbf98_idx',
            old_name='hotel_reserva_habitacion_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='hotel_reser_tenant__321fd8_idx',
            old_name='hotel_reserva_tenant_estado_idx',
        ),
        migrations.AddField(
            model_name='huesped',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI (Perú)'), ('carnet_extranjeria', 'Carné de extranjería (CE)'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro documento')], default='dni', help_text='DNI para peruanos; CE, pasaporte u otro para extranjeros.', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Depósito recibido al momento del check-in', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='documentos_recibidos',
            field=models.BooleanField(default=False, help_text='Indica si se recibieron los documentos de identidad', verbose_name='Documentos Recibidos'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='empleado',
            field=models.CharField(blank=True, help_text='Nombre del empleado que realizó el check-in', max_length=100, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el check-in', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales del check-in', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='reserva',
            field=models.OneToOneField(help_text='Reserva asociada al check-in', on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='hotel.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='calificacion',
            field=models.IntegerField(blank=True, help_text='Calificación del servicio (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='danos_observados',
            field=models.TextField(blank=True, help_text='Descripción de daños o problemas encontrados en la habitación', verbose_name='Daños Observados'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el check-out', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('yape', 'Yape'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', help_text='Método utilizado para el pago', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales del check-out', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='reserva',
            field=models.OneToOneField(help_text='Reserva asociada al check-out', on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='hotel.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, help_text='Monto total pagado al momento del check-out', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Pagado'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(help_text='Número máximo de personas que puede alojar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la habitación', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('limpieza', 'En Limpieza'), ('reservada', 'Reservada')], default='disponible', help_text='Estado actual de la habitación', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio_noche',
            field=models.DecimalField(decimal_places=2, help_text='Precio base por noche en soles (PEN)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por noche (soles)'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='servicios',
            field=models.TextField(blank=True, help_text='Servicios incluidos (WiFi, TV, minibar, etc.)', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='apellidos',
            field=models.CharField(help_text='Apellidos del huésped', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='documento_identidad',
            field=models.CharField(help_text='Número del DNI, CE, pasaporte, etc. (único por hotel junto al tipo)', max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el huésped', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='preferencias',
            field=models.TextField(blank=True, help_text='Preferencias especiales del huésped (cama extra, piso alto, etc.)', verbose_name='Preferencias'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('checkout', 'Check-out Realizado'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la reserva', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(help_text='Fecha en que el huésped ingresará al hotel', verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_salida_prevista',
            field=models.DateTimeField(blank=True, help_text='Opcional: para estadías cortas por horas (walk-in u otras), hora prevista de check-out. Si no aplica, quede vacío y se usa solo la fecha de salida.', null=True, verbose_name='Salida prevista (fecha y hora)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(help_text='Fecha en que el huésped saldrá del hotel', verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(help_text='Habitación reservada', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.habitacion', verbose_name='Habitación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(help_text='Huésped que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.huesped', verbose_name='Huésped'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la reserva', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_huespedes',
            field=models.IntegerField(help_text='Cantidad de personas que se alojarán', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Huéspedes'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, help_text='Total en soles (noches × precio/noche)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio total (soles)'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['fecha_hora'], name='hotel_check_fecha_h_7a5c98_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['fecha_hora'], name='hotel_check_fecha_h_54b159_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['metodo_pago'], name='hotel_check_metodo__0c5fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['tenant', 'numero'], name='hotel_habit_tenant__c1db4b_idx'),
        ),
        migrations.AddIndex(
            model_name='huesped',
            index=models.Index(fields=['tenant', 'tipo_documento', 'documento_identidad'], name='hotel_huesp_tenant__1da239_idx'),
        ),
        migrations.AddConstraint(
            model_name='huesped',
            constraint=models.UniqueConstraint(fields=('tenant', 'tipo_documento', 'documento_identidad'), name='uniq_huesped_tenant_tipo_documento'),
        ),
    ]
