# Generated by Django 4.2.7 on 2026-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_huesped_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(help_text='Día de checkout. Con política por noches, la salida máxima es ese día a las 12:00 (mediodía). Ej.: 1 noche = entrada un día y salida el día siguiente hasta mediodía.', verbose_name='Fecha de Salida'),
        ),
    ]
