# Generated by Django 6.0.1 on 2026-05-11 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_reserva_fecha_salida_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'user'], name='hotel_member_tenant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['tenant', 'fecha_entrada', 'fecha_salida'], name='hotel_reser_tenant__fa45c1_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['tenant', 'fecha_creacion'], name='hotel_reser_tenant__9e41eb_idx'),
        ),
    ]
