# Generated by Django 6.0.1 on 2026-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_scale_many_tenants_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
