# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_add_huesped_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='lugar_procedencia',
            new_name='lugar_residencia',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='lugar_residencia',
            field=models.CharField(
                help_text='Ciudad o lugar de residencia habitual del huésped',
                max_length=200,
                verbose_name='Lugar de residencia',
            ),
        ),
        migrations.AddField(
            model_name='huesped',
            name='motivo_viaje',
            field=models.CharField(
                choices=[
                    ('turismo', 'Turismo'),
                    ('negocios', 'Negocios'),
                    ('trabajo', 'Trabajo'),
                    ('estudios', 'Estudios'),
                    ('visita_familiar', 'Visita familiar'),
                    ('salud', 'Salud'),
                ],
                default='turismo',
                max_length=30,
                verbose_name='Motivo de viaje',
            ),
        ),
    ]
