# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_huesped_residencia_motivo_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='email',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='preferencias',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='notas',
        ),
    ]
